# Generated by Django 2.0.13 on 2019-04-18 14:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Title')),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тег Description')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег H1')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Keywords')),
                ('slug', models.SlugField(default='slug', unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=200)),
                ('preview', models.TextField(default='Еще одна рекламная система...', verbose_name='Краткое описание рекламной системы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Title')),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тег Description')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег H1')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Keywords')),
                ('slug', models.SlugField(default='slug', unique=True, verbose_name='URL')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название площадки')),
                ('preview', models.TextField(default='Еще одна сомнительная площадка...', verbose_name='Краткое описание площадки')),
                ('content', ckeditor.fields.RichTextField(default='content', verbose_name='Комментарий о площадке')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='preview',
            field=models.TextField(default='Очередная ненужная тематика...', verbose_name='Краткое описание тематики'),
        ),
        migrations.AddField(
            model_name='place',
            name='theme',
            field=models.ManyToManyField(help_text='Выберите тематику площадки', to='places.Theme', verbose_name='Тематика площадки'),
        ),
    ]
