# Generated by Django 2.0.13 on 2019-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190418_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='company',
            field=models.ManyToManyField(help_text='Выберите поставщика рекламы', to='places.Company', verbose_name='Поставщик рекламы'),
        ),
    ]
