# Generated by Django 2.0.13 on 2019-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.ManyToManyField(help_text='Выберите тему этой статьи', to='blog.Theme'),
        ),
    ]
