# Generated by Django 2.0.13 on 2019-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(default='Еще одна отличная статья...'),
        ),
        migrations.AddField(
            model_name='post',
            name='slink',
            field=models.CharField(default='slink', max_length=200),
        ),
    ]
