# Generated by Django 2.0.13 on 2019-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slink',
            field=models.CharField(default='slink', max_length=200),
        ),
    ]
