# Generated by Django 2.0.13 on 2019-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_theme_slink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slink',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
