# Generated by Django 2.0.13 on 2019-04-15 09:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190415_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='slink',
        ),
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default='slug', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='content', verbose_name='Содержимое статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Тег Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='h1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название статьи (для людей)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(default='Еще одна отличная статья...', verbose_name='Описание для анонса статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ManyToManyField(help_text='Выберите тему этой статьи', to='blog.Theme', verbose_name='Темы статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Title'),
        ),
    ]
