# Generated by Django 2.0.13 on 2019-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_theme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='URL'),
        ),
    ]
