# Generated by Django 2.0.13 on 2019-04-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190415_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default='slug', unique=True, verbose_name='URL'),
        ),
    ]
