# Generated by Django 2.0.13 on 2019-04-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190415_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Лучший пост?'),
        ),
    ]
