# Generated by Django 2.0.13 on 2019-04-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190418_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Тег Description'),
        ),
        migrations.AddField(
            model_name='theme',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег H1'),
        ),
        migrations.AddField(
            model_name='theme',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Keywords'),
        ),
        migrations.AddField(
            model_name='theme',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Title'),
        ),
    ]
