# Generated by Django 2.0.13 on 2019-04-29 12:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Title')),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тег Description')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег H1')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Keywords')),
                ('slug', models.SlugField(default='slug', unique=True, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(default='content', verbose_name='Содержимое страницы')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
